name       : haskell-unicode-transforms
version    : 0.3.0
release    : 1
source     :
    - http://hackage.haskell.org/package/unicode-transforms-0.3.0/unicode-transforms-0.3.0.tar.gz : 2dc25ead8d19598f6833a490ef1b1f29b9c1f987c8224fd99be6820535aa5245
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast Unicode 9.0 normalization in Haskell (NFC, NFKC, NFD, NFKD). 
description: |
    Fast Unicode 9.0 normalization in Haskell (NFC, NFKC, NFD, NFKD). 
builddeps  :
    - haskell-bitarray
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
