name       : haskell-unicode-transforms
version    : 0.3.4
release    : 3
source     :
    - https://hackage.haskell.org/package/unicode-transforms-0.3.4/unicode-transforms-0.3.4.tar.gz : 829eaccba7d2e3d642d0cf60bbab403a6a5673db64284c02abf3ee3e8d5c0852
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast Unicode 9.0 normalization in Haskell (NFC, NFKC, NFD, NFKD).
description: "Fast Unicode 9.0 normalization in Haskell (NFC, NFKC, NFD, NFKD). \n"
builddeps  :
    - haskell-bitarray
    - haskell-cabal-install
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
