name       : haskell-unicode-transforms
version    : 0.2.1
release    : 2
source     :
    - http://hackage.haskell.org/package/unicode-transforms-0.2.1/unicode-transforms-0.2.1.tar.gz : 1d8baa0de3c58685aa1e476961f7f3765395ba257d79258c66e86b06a87f3abc
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast Unicode 9.0 normalization in Haskell (NFC, NFKC, NFD, NFKD).
description: "Fast Unicode 9.0 normalization in Haskell (NFC, NFKC, NFD, NFKD). \n"
builddeps  :
    - haskell-bitarray
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
